language: ruby
cache: bundler
rvm:
- jruby-19mode
notifications:
  email:
  - tech@amicushq.com
  campfire:
    rooms:
      secure: ARqRo8P4LFNUNiZ+dLatchrDJoclyCST5SfLbM2z18Cf+LPzIQ06oXwpU9weRvcBwy+CrPcmIOPJDD7A6XzFPjO9zGMj/uByuVxenLAublFJiLz1zmIvg6zazF2VfFwD8r+NWbdqn+tJnGAqu1H04PpjHf+cy5149Az0Vet0HUY=
branches:
  only:
  - master
  - production
script:
  - RAILS_ENV=test AMICUS_ENV=ci jruby -S bundle exec rake ci:setup:rspec spec
services:
  - mongodb
  - redis-server
source_key: LS0tLS1CRUdJTiBSU0EgUFJJVkFURSBLRVktLS0tLQpNSUlFcEFJQkFBS0NBUUVBcW9hdFJ5cG5rYUlYV01wajFwOFRFdjhSTERaK3MyTks3Yzd4R04zK1ppcmVTaDZZCnFwdWwydzVveGYydVYrMTR3eHhVek9HcnVWR0U0RjVFRk9IdkJJZEdLT25HYzJiaXZMck8xekpGUytFckloMEEKSUhpQVFxL0dwOGRJYkFNMEtReHpadG5oM3RQYnFleUZEZmVQcmIwUmVvcXBxRlc2akdHSXhZRS9RS2hSOGJ3VQpzd2FJVmY1YVg5Rk9nTHgxbUtqTGVpYXBpSWZUQThGeFIrSmIxc0FNbktGbzhLU2JCemZhSU9qNGxTOGszRU54Ck9EZmxPMnhTNzg0ZGdIZHp4TG4zaEl4WlVUa0NKY3lsK1FQUjczMDZVNVltMmMzOXZwNWJERG03SllsY1B2bWgKZ2FkcFJDelJVZExNdlRmZHhXSk10NzMwMFVvdjVDYW43QWFvclFJREFRQUJBb0lCQVFDSmd4dGVwU3BwdlUyWQpjM1U1VUlSQU1HSTN4aVk4SU5qK2xuL0Q3dGpFcU5NaThETnFlU094VjVoVCtUTkxncHQ4czI4SzNQenU3M2I0CnUrdW83MTBneUxsaUtzcTJxd1F5NzIzM0NYbnFLOFR0dUhjdXVCMnVLVE5JZnlLK3Y0S2ppMy9RTSttNkdCd3UKbGlYaDBuNFJ1OExKaitJcWRoOStMdlR0V0VHYXNCQjRkbWI4SWFQUThvYUFVRmlJTjRvVyt2VEIyb0VPbmU2cApjTXl0U2hOTXNkWUY5VXZWb0RrMENnVEZub210bTRMK1FJRXJ2QXl1dytSVitZZkE1QTl1bVhoVUNoR3RWbnlUCkE5MVYrcTNvRDBnamk5UUYwYnVFU3daT3MzV20yOGtHcnYrSXB6c2pHczd6YkE1cVJWeHV6bE0za21FdnM0WDcKMHdmb1JDYWRBb0dCQU5ZWWgzb1BIckJUeXgzWTU0ajBFSkI1enF5TDZ2cnA0Mk5MRWR5RC9iUUl5aU5lbTFpRgpsa0VmcGlpR0ZVZ05nMkY3ZVFGR1JiZzJFbnpOSlJRMUNHbmFJVnNIdlY4NDlwMDF1bndDWWViekZYNkEvSXBNCnBESitMbElmckxpcldOa3ZlL04yeEJ0bldVMXpIUERmWnhHeTF3R1M0YXVGN1NxUng4WDJKOHFUQW9HQkFNdm4KQzUzdFB0WlZwcGJLYWpjMHhhZGkzY1BJUEZFdHRha0lvUHNUSGlwU2RTUE5ZVWhGRHowTU1zTWVHUGVFbHRsSgo0WkgwSHJDcXVnNldnQWRGemxHRm1ySE5yOG14RCt6WkZzVFRsZzQzc2RuQkp2T1lReFAwZkhFM2FUUy9KcmtLCkp4b29QNXQ5b2VYYVlubW5LclA2UmFXRGtuY1BYTDNKOUVJUVVZZS9Bb0dBV1g4L2d1SzNMWGFadmd4aUhYb0oKUXB2b3JYQi85Z3UzcGxaSFRTdFA3dWFOdVdOZkJRNHkxVjVwa3g4WjNsam54dVJhblJISEswNVBSQ1J0ajVqcgp2M1FUNVgzQ3gvK0QrQXZ4dk0weUo5ME42eWY0YWNmSUMrTjdjWkVVSHM1aUFjZzd4SGF0VzlkRUdZQTVaT2UrCnFrTmNaYWdFOWpLeUJjMlMrVW9CTUVrQ2dZQUw2Tzd3eG83SkRpK3cxeG5sSjV2ejd2NXRGU0VRek02emxPRnkKU09lV0tVTFdXSVM2Sis1LzdscDRzeVZhTDlCdjJMVG9SWTRWVzZPS2ZwZnoxTXY4VHdWK0pUbURXbWhIdVZadgpJTHkvRDltL2tseW9GZGkxTGE2bkhrbHkzMGR2djN3Uk54Q2dFSEtJYm4wYUJmMmtqWlhMMlNlUTlNRENCUzNUClBnakZHUUtCZ1FDUDRkSHVGMnZDT0NUL05qK05HVVkrZjFpMWMxejdvTjFoUVhRdGZpVy93Z0NEckxmM2FBaDQKdkxEZUdSZTY4L0V5ZmxDdXdlWTI4eW5LRmsxTlhrcWlCemZURUpoeGJxRTNmMHNMYU02SEo4Mm5abS9DWkdmdgovUkNVU21qNUE3YjM5ckYyeHhnb2JLVjdFV3BETVI0Z0F0RVk1Sk9PaCthTjd2M0Q3aVpCNkE9PQotLS0tLUVORCBSU0EgUFJJVkFURSBLRVktLS0tLQo=
env:
  global:
    - JRUBY_OPTS="-X-C"
    - JAVA_OPTS="-client -Xms1500m -Xmx1500m -XX:+TieredCompilation -XX:TieredStopAtLevel=1"
    - secure: kdCEVWgeOlvk2n6jcY6TPAryC6FAgzF3PJStxdlGHcIN9keL2S9Ty4yVjFxLEZFAT/WLKPlJoHA+ebj58Mzo/0tz3WfX6L1bpps0fIit6Hnq4f3uDJPC3GhhLuFfXA7CR5kJolSQKb/Y2Mt1biyOcOvHKbZBEMwTEZo6KvUhjr4=
    - secure: GWN9jBn09UcIB7zJw8TS9vq1SQP3sspQtEx3c6eidC5VvrhEsT60XPILkY3E/nWM7zHB4RPuJpbbAJf6DNUlzYVlxOj5S8iemHm7Sr9qFPyWlWA17slGUDAovgPXMYJNGO4D5TIKZ/e3oEUj6Lz5p5z75/GhJEEYdlGPhh0phMA=
