concurrency: 10
#message_queue: :redis_queue
#storage: :redis_storage
storage: :in_memory
message_queue:
  - :sqs
  - access_key_id: nada
    secret_access_key: nada
    sqs_endpoint: localhost
    sqs_port: 9324
    use_ssl: false
name: "donaghy_test"
queue_name: "donaghy_test"
services:
  - test_loaded_service
