concurrency: 10
#message_queue: :redis_queue
#storage: :redis_storage
storage: :in_memory
message_queue: :in_memory_queue
name: "donaghy_test"
queue_name: "donaghy_test"
services:
  - test_loaded_service
